#config_version=6

mode:
  start_events: start_mode_slingshots
  stop_events: stop_mode_slingshots
  priority: 200

shots: 
  slingshot_left:
    switch: s_sling_left
  slingshot_right:
    switch: s_sling_right 
#Shot_groups: egal, welcher Slingshot getroffen wird, mach etwas:
shot_groups:
  slingshots:
    shots: slingshot_left, slingshot_right     

variable_player:
  slingshots_hit:
    score: 1_000