#config_version=6

coils:
#J8
  c_flipper_right_main:
    number: 1-0-6
    default_pulse_ms: 35
  c_flipper_right_hold:
    number: 1-0-5
    allow_enable: true    
  c_flipper_right_upper_main:
    number: 1-0-4
    default_pulse_ms: 35
  c_flipper_right_upper_hold:
    number: 1-0-3
    allow_enable: true      
  c_drain_eject:
    number: 1-0-0
    default_pulse_ms: 20
  c_trough_release:
    number: 1-0-7
    default_pulse_ms: 20  
#J7    
  c_flipper_left_main:
    number: 0-0-3
    default_pulse_ms: 35
  c_flipper_left_hold:
    number: 0-0-2
    allow_enable: true
  c_flipper_left_middle_main:
    number: 0-0-5
    default_pulse_ms: 25
  c_flipper_left_middle_hold:
    number: 0-0-4
    allow_enable: true
#J6    
  c_flipper_left_upper_main:
    number: 0-0-14
    default_pulse_ms: 15
  c_flipper_left_upper_hold:
    number: 0-0-13
    allow_enable: true  
  
 