#config_version=6

hardware:
  platform: opp
  driverboards: gen2    

opp:
  ports:
    - COM4
    - COM5 
  debug: true  
  baud: 115200  

machine:
  balls_installed: 3 
  min_balls: 1   

config:
  - config_ball_devices.yaml
  - config_coils.yaml
  - config_switches.yaml
  - config_common.yaml


modes:
  - attract
  - base
  - slingshots
  - hurryup

playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default 



virtual_platform_start_active_switches:
  - s_trough_1
  - s_trough_2
  - s_trough_3        